### ISSUE TITLE
Is there any way to download .m4a directly without creating blob

### ISSUE THREAD

**Issue by HMser** [codyandersan/TuneStation#1]

**Comment by codyandersan** [comment]
Yes, if you just want to allow the user to download the song directly and the name of the downloaded file doesn't matter, you can  use `window.location.href = url` in the `downloadSong` function in `src/components/Player/Player.js`. (there would be other ways too)

In TuneStation, I have used `blob` because I wanted custom names of the downloaded songs. The default ones were just a bunch of random letters. Also, downloading as a blob allows to efficiently display the progress of the download.

**Comment by HMser** [comment]
Ok thanks❤️
