### ISSUE TITLE
Download problem!!, instead of m4a now downloading mp4

### ISSUE THREAD

**Issue by HMser** [codyandersan/TuneStation#2]
![20230622_095718.jpg](https://github.com/codyandersan/TuneStation/assets/95879255/d34765b7-4204-4b93-a3c0-d6f672b09bf6)

**Comment by codyandersan** [comment]
@HMser, sorry but I am unable to reproduce the issue. I tried downloading the same song (Channa Mereya) and some others too, but in my case, the files are getting downloaded with `.m4a` extension only.

If the bug still exists, you should manually try renaming the file extension from `.m4a.mp4` to `.m4a`, as the issue seems to be with the JioSaavnAPI. Though the extension is `.mp4`, I assure you that it is actually a 320kbps audio.



(TuneStation was actually a very small hobby project, I would be eager to know how you discovered it and what is your feedback about it 😅)

**Comment by HMser** [comment]
Sorry I forgot to close the issue, now the problem is gone, it was fixed the next day, I think it was an api bug. 


I came to know about Tunestation through your JioSaavnAPI [issue](https://github.com/sumitkolhe/jiosaavn-api/issues/32), no words to say about the project, it's very beautiful,simple and functional, I'm still learning it.

**Comment by HMser** [comment]
I think it was an api bug
